In [1]:
import numpy as np
import pandas as pd

In [2]:
stores=pd.read_csv("stores.csv")
stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2

In [7]:
# Find the number of row and columns
print(stores.shape)

(32, 15)

In [8]:
# Display its column labels.
print(stores.columns)

Index(['StoreCode', 'StoreName', 'StoreType', 'Location', 'OperatingCost',
       'Staff_Cnt', 'TotalSales', 'Total_Customers', 'AcqCostPercust',
       'BasketSize', 'ProfitPercust', 'OwnStore', 'OnlinePresence', 'Tenure',
       'StoreSegment'],
      dtype='str')

In [10]:
# Display first ten records.
stores.head(10)

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2
5,STR106,Apparel Zone,Apparel,Delhi,18.1,60,225.0,105,2.76,3.460,20.22,1,0,3,1
6,STR107,Fashion Bazar,Apparel,Delhi,14.3,80,360.0,245,3.21,3.570,15.84,0,0,3,4
7,STR108,Digital Bazar,Electronincs,Delhi,24.4,40,146.7,62,3.69,3.190,20.00,1,0,4,2
8,STR109,Electronics Zone,Electronincs,Chennai,22.8,40,140.8,95,3.92,3.150,22.90,1,0,4,2
9,STR110,Apparel Zone,Apparel,Chennai,19.2,60,167.6,123,3.92,3.440,18.30,1,0,4,4

In [11]:
# Display last 10 records
stores.tail(10)

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
22,STR123,Fashion Bazar,Apparel,Mumbai,15.2,80,304.0,150,3.15,3.435,17.30,0,0,3,2
23,STR124,Digital Bazar,Electronincs,Mumbai,13.3,80,350.0,245,3.73,3.840,15.41,0,0,3,4
24,STR125,Electronics Zone,Electronincs,Kolkata,19.2,80,400.0,175,3.08,3.845,17.05,0,0,3,2
25,STR126,Apparel Zone,Apparel,Kolkata,27.3,40,79.0,66,4.08,1.935,18.90,1,1,4,1
26,STR127,Super Bazar,Super Market,Kolkata,26.0,40,120.3,91,4.43,2.140,16.70,0,1,5,2
27,STR128,Super Market,Super Market,Kolkata,30.4,40,95.1,113,3.77,1.513,16.90,1,1,5,2
28,STR129,Central Store,Super Market,Kolkata,15.8,80,351.0,264,4.22,3.170,14.50,0,1,5,4
29,STR130,Apparel Zone,Apparel,Kolkata,19.7,60,145.0,175,3.62,2.770,15.50,0,1,5,4
30,STR131,Fashion Bazar,Apparel,Kolkata,15.0,80,301.0,335,3.54,3.570,14.60,0,1,5,4
31,STR132,Digital Bazar,Electronincs,Kolkata,21.4,40,121.0,109,4.11,2.780,18.60,1,1,4,2

In [12]:
# Select three random records
stores.sample(3)

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4
6,STR107,Fashion Bazar,Apparel,Delhi,14.3,80,360.0,245,3.21,3.570,15.84,0,0,3,4

In [13]:
# Display the data type of every columns
print(stores.dtypes)

StoreCode              str
StoreName              str
StoreType              str
Location               str
OperatingCost      float64
Staff_Cnt            int64
TotalSales         float64
Total_Customers      int64
AcqCostPercust     float64
BasketSize         float64
ProfitPercust      float64
OwnStore             int64
OnlinePresence       int64
Tenure               int64
StoreSegment         int64
dtype: object

In [14]:
# Determine the total number of elements
print(stores.size)

480

In [15]:
# Use info() to perform metadata auditing
stores.info()

<class 'pandas.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   StoreCode        32 non-null     str
 1   StoreName        32 non-null     str
 2   StoreType        32 non-null     str
 3   Location         32 non-null     str
 4   OperatingCost    32 non-null     float64
 5   Staff_Cnt        32 non-null     int64
 6   TotalSales       32 non-null     float64
 7   Total_Customers  32 non-null     int64
 8   AcqCostPercust   29 non-null     float64
 9   BasketSize       32 non-null     float64
 10  ProfitPercust    32 non-null     float64
 11  OwnStore         32 non-null     int64
 12  OnlinePresence   32 non-null     int64
 13  Tenure           32 non-null     int64
 14  StoreSegment     32 non-null     int64
dtypes: float64(5), int64(6), str(4)
memory usage: 5.0 KB

In [18]:
# Perform numerical data auditing on the stores DataFrame using describe() and transpose the result.
stores.describe().T

,count,mean,std,min,25%,50%,75%,max
OperatingCost,32.0,20.090625,6.026948,10.400,15.42500,19.200,22.80,33.900
Staff_Cnt,32.0,61.875000,17.859216,40.000,40.00000,60.000,80.00,80.000
TotalSales,32.0,230.721875,123.938694,71.100,120.82500,196.300,326.00,472.000
Total_Customers,32.0,146.687500,68.562868,52.000,96.50000,123.000,180.00,335.000
AcqCostPercust,29.0,3.651034,0.532664,2.760,3.15000,3.730,3.92,4.930
BasketSize,32.0,3.217250,0.978457,1.513,2.58125,3.325,3.61,5.424
ProfitPercust,32.0,17.848750,1.786943,14.500,16.89250,17.710,18.90,22.900
OwnStore,32.0,0.437500,0.504016,0.000,0.00000,0.000,1.00,1.000
OnlinePresence,32.0,0.406250,0.498991,0.000,0.00000,0.000,1.00,1.000
Tenure,32.0,3.687500,0.737804,3.000,3.00000,4.000,4.00,5.000
StoreSegment,32.0,2.625000,1.211504,1.000,2.00000,2.000,4.00,4.000

In [19]:
# Use describe(include='object') to audit the categorical columns .
stores.describe(include='object')

C:\Users\Ravindra Pal\AppData\Local\Temp\ipykernel_2732\1276108446.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  stores.describe(include='object')

       StoreCode     StoreName StoreType Location
count         32            32        32       32
unique        32             7         3        4
top       STR101  Apparel Zone   Apparel    Delhi
freq           1             8        12        8

In [25]:
# Select the StoreName and StoreType columns .
print(stores[['StoreName','StoreType']])

           StoreName     StoreType
0   Electronics Zone  Electronincs
1       Apparel Zone       Apparel
2        Super Bazar  Super Market
3       Super Market  Super Market
4      Central Store  Super Market
5       Apparel Zone       Apparel
6      Fashion Bazar       Apparel
7      Digital Bazar  Electronincs
8   Electronics Zone  Electronincs
9       Apparel Zone       Apparel
10       Super Bazar  Super Market
11      Super Market  Super Market
12     Central Store  Super Market
13      Apparel Zone       Apparel
14     Fashion Bazar       Apparel
15     Digital Bazar  Electronincs
16  Electronics Zone  Electronincs
17      Apparel Zone       Apparel
18       Super Bazar  Super Market
19      Super Market  Super Market
20     Central Store  Super Market
21      Apparel Zone       Apparel
22     Fashion Bazar       Apparel
23     Digital Bazar  Electronincs
24  Electronics Zone  Electronincs
25      Apparel Zone       Apparel
26       Super Bazar  Super Market
27      Super Market  Super Market
28     Central Store  Super Market
29      Apparel Zone       Apparel
30     Fashion Bazar       Apparel
31     Digital Bazar  Electronincs

In [27]:
# A retail analyst needs only the store name, location, total sales, and total customers for a reporting table.Select these four columns from stores.
stores[['StoreName','Location','TotalSales', 'Total_Customers']]

           StoreName Location  TotalSales  Total_Customers
0   Electronics Zone    Delhi       160.0              110
1       Apparel Zone    Delhi       160.0              110
2        Super Bazar    Delhi       108.0               93
3       Super Market    Delhi       258.0              110
4      Central Store    Delhi       360.0              175
5       Apparel Zone    Delhi       225.0              105
6      Fashion Bazar    Delhi       360.0              245
7      Digital Bazar    Delhi       146.7               62
8   Electronics Zone  Chennai       140.8               95
9       Apparel Zone  Chennai       167.6              123
10       Super Bazar  Chennai       167.6              123
11      Super Market  Chennai       275.8              180
12     Central Store  Chennai       275.8              180
13      Apparel Zone  Chennai       275.8              180
14     Fashion Bazar  Chennai       472.0              205
15     Digital Bazar  Chennai       460.0              215
16  Electronics Zone   Mumbai       440.0              230
17      Apparel Zone   Mumbai        78.7               66
18       Super Bazar   Mumbai        75.7               52
19      Super Market   Mumbai        71.1               65
20     Central Store   Mumbai       120.1               97
21      Apparel Zone   Mumbai       318.0              150
22     Fashion Bazar   Mumbai       304.0              150
23     Digital Bazar   Mumbai       350.0              245
24  Electronics Zone  Kolkata       400.0              175
25      Apparel Zone  Kolkata        79.0               66
26       Super Bazar  Kolkata       120.3               91
27      Super Market  Kolkata        95.1              113
28     Central Store  Kolkata       351.0              264
29      Apparel Zone  Kolkata       145.0              175
30     Fashion Bazar  Kolkata       301.0              335
31     Digital Bazar  Kolkata       121.0              109

In [31]:
# Use .loc to select all rows and the StoreName and StoreType column
stores.loc[:,['StoreName','StoreType']]

           StoreName     StoreType
0   Electronics Zone  Electronincs
1       Apparel Zone       Apparel
2        Super Bazar  Super Market
3       Super Market  Super Market
4      Central Store  Super Market
5       Apparel Zone       Apparel
6      Fashion Bazar       Apparel
7      Digital Bazar  Electronincs
8   Electronics Zone  Electronincs
9       Apparel Zone       Apparel
10       Super Bazar  Super Market
11      Super Market  Super Market
12     Central Store  Super Market
13      Apparel Zone       Apparel
14     Fashion Bazar       Apparel
15     Digital Bazar  Electronincs
16  Electronics Zone  Electronincs
17      Apparel Zone       Apparel
18       Super Bazar  Super Market
19      Super Market  Super Market
20     Central Store  Super Market
21      Apparel Zone       Apparel
22     Fashion Bazar       Apparel
23     Digital Bazar  Electronincs
24  Electronics Zone  Electronincs
25      Apparel Zone       Apparel
26       Super Bazar  Super Market
27      Super Market  Super Market
28     Central Store  Super Market
29      Apparel Zone       Apparel
30     Fashion Bazar       Apparel
31     Digital Bazar  Electronincs

In [32]:
# Use .loc to create a report containing StoreCode, StoreName, Location and TotalSales.
stores.loc[:,['StoreCode','StoreName','Location','TotalSales']]

   StoreCode         StoreName Location  TotalSales
0     STR101  Electronics Zone    Delhi       160.0
1     STR102      Apparel Zone    Delhi       160.0
2     STR103       Super Bazar    Delhi       108.0
3     STR104      Super Market    Delhi       258.0
4     STR105     Central Store    Delhi       360.0
5     STR106      Apparel Zone    Delhi       225.0
6     STR107     Fashion Bazar    Delhi       360.0
7     STR108     Digital Bazar    Delhi       146.7
8     STR109  Electronics Zone  Chennai       140.8
9     STR110      Apparel Zone  Chennai       167.6
10    STR111       Super Bazar  Chennai       167.6
11    STR112      Super Market  Chennai       275.8
12    STR113     Central Store  Chennai       275.8
13    STR114      Apparel Zone  Chennai       275.8
14    STR115     Fashion Bazar  Chennai       472.0
15    STR116     Digital Bazar  Chennai       460.0
16    STR117  Electronics Zone   Mumbai       440.0
17    STR118      Apparel Zone   Mumbai        78.7
18    STR119       Super Bazar   Mumbai        75.7
19    STR120      Super Market   Mumbai        71.1
20    STR121     Central Store   Mumbai       120.1
21    STR122      Apparel Zone   Mumbai       318.0
22    STR123     Fashion Bazar   Mumbai       304.0
23    STR124     Digital Bazar   Mumbai       350.0
24    STR125  Electronics Zone  Kolkata       400.0
25    STR126      Apparel Zone  Kolkata        79.0
26    STR127       Super Bazar  Kolkata       120.3
27    STR128      Super Market  Kolkata        95.1
28    STR129     Central Store  Kolkata       351.0
29    STR130      Apparel Zone  Kolkata       145.0
30    STR131     Fashion Bazar  Kolkata       301.0
31    STR132     Digital Bazar  Kolkata       121.0

In [34]:
# Create a reusable selection expression that returns all rows but only the columns StoreName, StoreType, OperatingCost, and TotalSales.
selected_columns=['StoreName','StoreType','OperatingCost','TotalSales']
result = stores.loc[:,selected_columns]
print(result)

           StoreName     StoreType  OperatingCost  TotalSales
0   Electronics Zone  Electronincs           21.0       160.0
1       Apparel Zone       Apparel           21.0       160.0
2        Super Bazar  Super Market           22.8       108.0
3       Super Market  Super Market           21.4       258.0
4      Central Store  Super Market           18.7       360.0
5       Apparel Zone       Apparel           18.1       225.0
6      Fashion Bazar       Apparel           14.3       360.0
7      Digital Bazar  Electronincs           24.4       146.7
8   Electronics Zone  Electronincs           22.8       140.8
9       Apparel Zone       Apparel           19.2       167.6
10       Super Bazar  Super Market           17.8       167.6
11      Super Market  Super Market           16.4       275.8
12     Central Store  Super Market           17.3       275.8
13      Apparel Zone       Apparel           15.2       275.8
14     Fashion Bazar       Apparel           10.4       472.0
15     Digital Bazar  Electronincs           10.4       460.0
16  Electronics Zone  Electronincs           14.7       440.0
17      Apparel Zone       Apparel           32.4        78.7
18       Super Bazar  Super Market           30.4        75.7
19      Super Market  Super Market           33.9        71.1
20     Central Store  Super Market           21.5       120.1
21      Apparel Zone       Apparel           15.5       318.0
22     Fashion Bazar       Apparel           15.2       304.0
23     Digital Bazar  Electronincs           13.3       350.0
24  Electronics Zone  Electronincs           19.2       400.0
25      Apparel Zone       Apparel           27.3        79.0
26       Super Bazar  Super Market           26.0       120.3
27      Super Market  Super Market           30.4        95.1
28     Central Store  Super Market           15.8       351.0
29      Apparel Zone       Apparel           19.7       145.0
30     Fashion Bazar       Apparel           15.0       301.0
31     Digital Bazar  Electronincs           21.4       121.0

In [36]:
# Select the numerical columns OperatingCost, Staff_Cnt, TotalSales, and Total_Customers.
# numeric_data=
stores[['OperatingCost','Staff_Cnt','TotalSales','Total_Customers']]
# print(numeric_data)

    OperatingCost  Staff_Cnt  TotalSales  Total_Customers
0            21.0         60       160.0              110
1            21.0         60       160.0              110
2            22.8         40       108.0               93
3            21.4         60       258.0              110
4            18.7         80       360.0              175
5            18.1         60       225.0              105
6            14.3         80       360.0              245
7            24.4         40       146.7               62
8            22.8         40       140.8               95
9            19.2         60       167.6              123
10           17.8         60       167.6              123
11           16.4         80       275.8              180
12           17.3         80       275.8              180
13           15.2         80       275.8              180
14           10.4         80       472.0              205
15           10.4         80       460.0              215
16           14.7         80       440.0              230
17           32.4         40        78.7               66
18           30.4         40        75.7               52
19           33.9         40        71.1               65
20           21.5         40       120.1               97
21           15.5         80       318.0              150
22           15.2         80       304.0              150
23           13.3         80       350.0              245
24           19.2         80       400.0              175
25           27.3         40        79.0               66
26           26.0         40       120.3               91
27           30.4         40        95.1              113
28           15.8         80       351.0              264
29           19.7         60       145.0              175
30           15.0         80       301.0              335
31           21.4         40       121.0              109

In [38]:
# Create a DataFrame containing only BasketSize, ProfitPercust, Tenure and StoreSegment.
stores[['BasketSize','ProfitPercust','Tenure','StoreSegment']]

    BasketSize  ProfitPercust  Tenure  StoreSegment
0        2.620          16.46       4             4
1        2.875          17.02       4             4
2        2.320          18.61       4             1
3        3.215          19.44       3             1
4        3.440          17.02       3             2
5        3.460          20.22       3             1
6        3.570          15.84       3             4
7        3.190          20.00       4             2
8        3.150          22.90       4             2
9        3.440          18.30       4             4
10       3.440          18.90       4             4
11       4.070          17.40       3             3
12       3.730          17.60       3             3
13       3.780          18.00       3             3
14       5.250          17.98       3             4
15       5.424          17.82       3             4
16       5.345          17.42       3             4
17       2.200          19.47       4             1
18       1.615          18.52       4             2
19       1.835          19.90       4             1
20       2.465          20.01       3             1
21       3.520          16.87       3             2
22       3.435          17.30       3             2
23       3.840          15.41       3             4
24       3.845          17.05       3             2
25       1.935          18.90       4             1
26       2.140          16.70       5             2
27       1.513          16.90       5             2
28       3.170          14.50       5             4
29       2.770          15.50       5             4
30       3.570          14.60       5             4
31       2.780          18.60       4             2

In [41]:
# Select all integer and floating-point columns from stores using select_dtypes() and display the first five rows.
stores.select_dtypes(include=[int,float]).head()

,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment
0,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4
1,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4
2,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1
3,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1
4,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2

In [43]:
# Select all columns from stores except integer and floating-point columns.
stores.select_dtypes(exclude=[int,float])

   StoreCode         StoreName     StoreType Location
0     STR101  Electronics Zone  Electronincs    Delhi
1     STR102      Apparel Zone       Apparel    Delhi
2     STR103       Super Bazar  Super Market    Delhi
3     STR104      Super Market  Super Market    Delhi
4     STR105     Central Store  Super Market    Delhi
5     STR106      Apparel Zone       Apparel    Delhi
6     STR107     Fashion Bazar       Apparel    Delhi
7     STR108     Digital Bazar  Electronincs    Delhi
8     STR109  Electronics Zone  Electronincs  Chennai
9     STR110      Apparel Zone       Apparel  Chennai
10    STR111       Super Bazar  Super Market  Chennai
11    STR112      Super Market  Super Market  Chennai
12    STR113     Central Store  Super Market  Chennai
13    STR114      Apparel Zone       Apparel  Chennai
14    STR115     Fashion Bazar       Apparel  Chennai
15    STR116     Digital Bazar  Electronincs  Chennai
16    STR117  Electronics Zone  Electronincs   Mumbai
17    STR118      Apparel Zone       Apparel   Mumbai
18    STR119       Super Bazar  Super Market   Mumbai
19    STR120      Super Market  Super Market   Mumbai
20    STR121     Central Store  Super Market   Mumbai
21    STR122      Apparel Zone       Apparel   Mumbai
22    STR123     Fashion Bazar       Apparel   Mumbai
23    STR124     Digital Bazar  Electronincs   Mumbai
24    STR125  Electronics Zone  Electronincs  Kolkata
25    STR126      Apparel Zone       Apparel  Kolkata
26    STR127       Super Bazar  Super Market  Kolkata
27    STR128      Super Market  Super Market  Kolkata
28    STR129     Central Store  Super Market  Kolkata
29    STR130      Apparel Zone       Apparel  Kolkata
30    STR131     Fashion Bazar       Apparel  Kolkata
31    STR132     Digital Bazar  Electronincs  Kolkata

In [4]:
# Vectorization: Vectorization means applying an operation to an entire array-like structure rather than manually processing each row with a Python loop.

# To define calculated variabled/derived variables
# Operating Cost+Total Customers*Acq Cost Per Cust
stores['TotalCost']=stores.OperatingCost + stores.Total_Customers*stores.AcqCostPercust
stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,TotalCost
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,450.00
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,450.00
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,380.85
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,360.20
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,569.95

In [5]:
# Calcuate 18% GST on Sales in 'GST' Column.
stores['GST']=0.18*stores['TotalSales']
stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,TotalCost,GST
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,450.00,28.80
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,450.00,28.80
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,380.85,19.44
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,360.20,46.44
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,569.95,64.80

In [6]:
# assign: The assign() operation is used to create new columns while returning a DataFrame containing the new columns.
stores=stores.assign(TotalCost2=stores.OperatingCost+stores.Total_Customers*stores.AcqCostPercust,CP1=0.1)
stores.head()

,StoreCode,StoreName,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,TotalCost,GST,TotalCost2,CP1
0,STR101,Electronics Zone,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,450.00,28.80,450.00,0.1
1,STR102,Apparel Zone,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,450.00,28.80,450.00,0.1
2,STR103,Super Bazar,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,380.85,19.44,380.85,0.1
3,STR104,Super Market,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,360.20,46.44,360.20,0.1
4,STR105,Central Store,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,569.95,64.80,569.95,0.1

In [7]:
# insert- Not an efficient operation
stores.insert(2,'TotalCost3',stores.OperatingCost+stores.Total_Customers*stores.AcqCostPercust)
stores.head()

,StoreCode,StoreName,TotalCost3,StoreType,Location,OperatingCost,Staff_Cnt,TotalSales,Total_Customers,AcqCostPercust,BasketSize,ProfitPercust,OwnStore,OnlinePresence,Tenure,StoreSegment,TotalCost,GST,TotalCost2,CP1
0,STR101,Electronics Zone,450.00,Electronincs,Delhi,21.0,60,160.0,110,3.90,2.620,16.46,0,1,4,4,450.00,28.80,450.00,0.1
1,STR102,Apparel Zone,450.00,Apparel,Delhi,21.0,60,160.0,110,3.90,2.875,17.02,0,1,4,4,450.00,28.80,450.00,0.1
2,STR103,Super Bazar,380.85,Super Market,Delhi,22.8,40,108.0,93,3.85,2.320,18.61,1,1,4,1,380.85,19.44,380.85,0.1
3,STR104,Super Market,360.20,Super Market,Delhi,21.4,60,258.0,110,3.08,3.215,19.44,1,0,3,1,360.20,46.44,360.20,0.1
4,STR105,Central Store,569.95,Super Market,Delhi,18.7,80,360.0,175,3.15,3.440,17.02,0,0,3,2,569.95,64.80,569.95,0.1

In [12]:
# Task: Apply a 5% discount for superMarket Stores on Sales and 10% discount for everything else.
discount=[]
for index,row in stores.iterrows():
    if row['Store_Type']=='SuperMarket':
        discount.append(row['Sales']*0.05)
    else:
        discount.append(row['Sales']*0.1)
stores['discount']=discount
stores.head()

KeyError: 'Store_Type'